/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData music = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData params = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_1 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_secret = IconData(0xf21b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_double = IconData(0xf560, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
